version: 2.1  # Specifying workflow version

jobs:
  build:
    docker:
      - image: python:3.11.4-alpine  # Using a pre-built Python image for efficiency

    steps:
      - checkout  # Fetch code from Git repository

      - run:
          name: Install dependencies
          command: |
            python3 -m venv /opt/venv  # Create a virtual environment
            . /opt/venv/bin/activate  # Activate the virtual environment
            pip install -r requirements.txt  # Install dependencies from requirements.txt

      - run:   # Linting step (assuming flake8 is in the virtual environment)
          name: Run Flake8 linting
          command: |
            flake8 .

      - run:   # Testing step
          name: Run tests
          command: python manage.py test

workflows:
  build_and_test:  # More descriptive workflow name
    jobs:
      - build  # Reference the build job defined earlier
