version: 2.1

jobs:
  build:
    docker:
      - image: python:3.11.4-alpine

    working_directory: /app

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            python3 -m venv /opt/venv
            /opt/venv/bin/pip install --upgrade pip
            /opt/venv/bin/pip install -r requirements.txt

      # Linting with flake8
      - run:
          name: Run Flake8 linting
          command: |
            /opt/venv/bin/flake8 .

      # Run tests
      - run:
          name: Run tests
          command: |
            /python manage.py test

workflows:
  version: 2
  build:
    jobs:
      - build
